services:
  admin:
    image: ghcr.io/crosstalk-solutions/project-nomad:latest
    container_name: nomad_admin
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /opt/project-nomad/storage:/app/storage
      - /tmp/nomad-disk-info.json:/app/storage/disk-info.json
      - /var/run/docker.sock:/var/run/docker.sock # Allows the admin service to communicate with the Host's Docker daemon
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    environment:
      - NODE_ENV=production
      - PORT=8080
      - LOG_LEVEL=debug
      - APP_KEY=replaceme
      - HOST=0.0.0.0
      - URL=replaceme
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=nomad
      - DB_USER=nomad_user
      - DB_PASSWORD=replaceme
      - DB_NAME=nomad
      - DB_SSL=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  dozzle:
    image: amir20/dozzle:latest
    container_name: nomad_dozzle
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allows Dozzle to read logs from the Host's Docker daemon
    environment:
      - DOZZLE_ENABLE_ACTIONS=true # Enables the action buttons (restart, stop, etc.)
      - DOZZLE_ENABLE_SHELL=true  # Enables web-based shell access
  mysql:
    image: mysql:8.0
    container_name: nomad_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=replaceme
      - MYSQL_DATABASE=nomad
      - MYSQL_USER=nomad_user
      - MYSQL_PASSWORD=replaceme
    volumes:
      - /opt/project-nomad/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
  redis:
    image: redis:7-alpine
    container_name: nomad_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /opt/project-nomad/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3